blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import static
from blog.settings import MEDIA_ROOT, MEDIA_URL
from show import views
from utils.upload_images import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include(('myblog.urls', 'myblog'), namespace='myblog')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('show/', include(('show.urls', 'show'), namespace='show')),
    # ip直接访问,
    path('', views.a_index),
    # kindeditor编辑器上传图片地址
    re_path(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

myblog/urls.py
from django.urls import path
from myblog import views

urlpatterns = [
    # 文章
    path('article/', views.article, name='article'),
    path('add_article/', views.add_article, name='add_article'),
    path('update_article/', views.update_article, name='update_article'),
    path('delete_article/', views.delete_article, name='delete_article'),
    # 栏目
    path('category/', views.category, name='category'),
    path('update_category/', views.update_category, name='update_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('delete_session/', views.delete_session, name='delete_session'),
    # 评论
    path('comment/', views.comment, name='comment'),
    # 删除评论
    path('del_comment/', views.del_comment, name='del_comment'),
    # 搜索实现
    path('search_fun/', views.search_fun, name='search_fun'),

]

show/urls.py
from django.urls import path

from show import views

urlpatterns = [
    path('a_index/', views.a_index, name='a_index'),
    # path('a_services/', views.a_services, name='a_services'),
    path('a_single/', views.a_single, name='a_single'),
    path('a_about/', views.a_about, name='a_about'),
    path('a_tag/', views.a_tag, name='a_tag'),

    # 搜索
    path('search/', views.search, name='search'),
    # 详情,留言
    path('a_contact', views.a_contact, name='a_contact'),
]

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('update/', views.update, name='update'),
    # 用户更多设置
    path('user_set/', views.user_set, name='user_set'),

]

templates/a_about.html
{% extends 'a_base.html' %}
{% block title %}
<title>关于作者</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-12" style="text-align:center;">
            {% if user.id %}

            <p class="mb-5"><img id="imgPhoto"
                         style="border-radius: 100px;border: none;"
                         width="200px" height="200px"
                         src="/media/{{user.img}}"/></p>

            <div class="row">
                <div class="col-xl-8 col-lg-12 mx-auto">
                    <h1 class="mb-3">关于</h1>
                    <p>用户名:{{user.name}}</p>
                    <p>详情:</p>
                    {{user.desc|safe}}
                </div>
            </div>

            <section class="probootstrap-section">
        <div class="container-fluid">
            <div class="row mb-5 justify-content-center">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-8 mx-auto">
                            <h2 class="h1 mb-5 mt-0">文章</h2>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="owl-carousel probootstrap-owl">
                        {% for art in user.user.all %}
                        <div class="item">
                            <a href="{% url 'show:a_single' %}?id={{art.id}}"><img src="/media/{{art.title_img}}"  width="370px" height="250px" title="{{art.title}}" /></a>
                            <div class="p-4 border border-top-0">
                                <h4>{{art.title}}</h4>
                                <p>{{art.describe}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>


        </div>
    </section>

            {% endif %}

            {% if no_user %}

            <p class="mb-5"><img id="imgPhoto"
                         style="border-radius: 100px;border: none;"
                         width="200px" height="200px"
                         src="/static/a_images/avtar.png"/></p>
            <div class="row">
                <div class="col-xl-8 col-lg-12 mx-auto">
                    <h1 class="mb-3">关于</h1>
                    <p>{{no_user}}</p>
                    <p><a href="{% url 'users:login' %}">登录后台</a></p>
                </div>
            </div>
            {% endif %}
        </div>

    </div>


</div>
{% endblock %}

templates/a_base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}

    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free HTML5 Website Template by ProBootstrap.com"/>
    <meta name="keywords"
          content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive"/>
    <meta name="author" content="ProBootstrap.com"/>

    <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet">

    <link rel="stylesheet" href="/static/a_css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/a_css/open-iconic-bootstrap.min.css">

    <link rel="stylesheet" href="/static/a_css/owl.carousel.min.css">
    <link rel="stylesheet" href="/static/a_css/owl.theme.default.min.css">

    <link rel="stylesheet" href="/static/a_css/icomoon.css">
    <link rel="stylesheet" href="/static/a_css/animate.css">
    <link rel="stylesheet" href="/static/a_css/style.css">
    <script>
        function search(){
        var val = document.getElementById('search').value
             console.log(val);
        }
</script>

</head>

<body>

<aside class="probootstrap-aside js-probootstrap-aside">
    <a href="#" class="probootstrap-close-menu js-probootstrap-close-menu d-md-none"><span
            class="oi oi-arrow-left"></span> Close</a>
    <div class="probootstrap-site-logo probootstrap-animate" data-animate-effect="fadeInLeft">
        <p class="mb-0"><input id="search" name="search" placeholder="输入标题或关键字"></p>
        <button onclick="search()" class="mb-2 d-block probootstrap-logo">搜索</button>
    </div>

    <div class="probootstrap-overflow">
        <nav class="probootstrap-nav">
            <ul>
                <li class="probootstrap-animate {% if flag == 1 %}active{% endif %}" data-animate-effect="fadeInLeft"><a
                        href="{% url 'show:a_index' %}">首页</a></li>
                <li class="probootstrap-animate {% if flag == 2 %}active{% endif %}" data-animate-effect="fadeInLeft"><a
                        href="{% url 'show:a_about' %}">作者</a></li>
                <li class="probootstrap-animate {% if flag == 3 %}active{% endif %}" data-animate-effect="fadeInLeft"><a
                        href="{% url 'show:a_tag' %}">标签</a>
                </li>
                {% if user.id %}
                <li class="probootstrap-animate" data-animate-effect="fadeInLeft"><a href="{% url 'myblog:article' %}">后台</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        <footer class="probootstrap-aside-footer probootstrap-animate" data-animate-effect="fadeInLeft">
            <ul class="list-unstyled d-flex probootstrap-aside-social">
                <!--<li><a href="#" class="p-2"><span class="icon-twitter"></span></a></li>
                <li><a href="#" class="p-2"><span class="icon-instagram"></span></a></li>
                <li><a href="#" class="p-2"><span class="icon-dribbble"></span></a></li>-->
            </ul>
            <p>&copy; 2017 ProBootstrap:Aside. <br> All Rights Reserved. More Templates </p>
        </footer>
    </div>
</aside>


<main role="main" class="probootstrap-main js-probootstrap-main">
    <div class="probootstrap-bar">
        <a href="#" class="probootstrap-toggle js-probootstrap-toggle"><span class="oi oi-menu"></span></a>
        <div class="probootstrap-main-site-logo"><a href="index.html">Aside</a></a></div>
    </div>

    {% block content %}
    {% endblock %}

</main>

<script src="/static/a_js/jquery-3.2.1.slim.min.js"></script>
<script src="/static/a_js/popper.min.js"></script>
<script src="/static/a_js/bootstrap.min.js"></script>
<script src="/static/a_js/owl.carousel.min.js"></script>
<script src="/static/a_js/jquery.waypoints.min.js"></script>
<script src="/static/a_js/imagesloaded.pkgd.min.js"></script>
<script src="/static/a_js/main.js"></script>
<script>
        function search(){
            var val = $("#search").val()
            window.location.href= '/show/search/?name='+val;
        }
    </script>

</body>
</html>

templates/a_index.html
{% extends 'a_base.html' %}
{% block title %}
<title>首页</title>
{% endblock %}
{% block content %}
<div class="card-columns">
    {% for art in art_list %}
    <div class="card">
        <a href="{% url 'show:a_single' %}?id={{art.id}}" title="{{art.title}}">
            <img class="card-img-top probootstrap-animate" src="/media/{{art.title_img}}" alt="Card image cap"
                 data-animate-effect="fadeIn">
        </a>
    </div>
    {% endfor %}
</div>
<div class="tlinks">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>

{% endblock %}

templates/a_single.html
{% extends 'a_base.html' %}
{% block title %}
<title>{{art.title}}详情</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-xl-8 col-lg-12">
            <div class="row">
                <div class="col-xl-8 col-lg-12 mx-auto">
                    <h1 class="mb-5">{{art.title}}</h1>
                    <h3 class="mb-3">文章出自:<a href="{% url 'show:a_contact' %}?id={{art.user_id}}">{{art.user.name}}</a></h3>
                    <h3 class="mb-3">文章栏目:{{art.col.name}}</h3>
                    <p>{{art.content|safe}}</p>
                    <h5 class="mb-3">文章标签:{% for l in art.lab.all %}{% if forloop.last%}标签{{forloop.counter}}:{{l.name}}{% else %}标签{{forloop.counter}}:{{l.name}}&nbsp;&nbsp;|&nbsp;&nbsp;{% endif %}{% endfor %}</h5>
                    <div>
                        <!--判断是否有上一篇-->
                        {% if has_prev %}
                        <a style="float:left" href="{% url 'show:a_single' %}?id={{art_prev.id}}" rel="prev"
                           title="{{ art_prev.title }}">
                            <<&nbsp;&nbsp;{{ art_prev.title }}
                        </a>
                        {% else %}
                        <a href="javascript:;" style="float:left">
                            没有文章啦!!!
                        </a>
                        {% endif %}

                        <!--判断是否有下一篇-->
                        {% if has_next %}
                        <a style="float:right" href="{% url 'show:a_single' %}?id={{art_next.id}}" rel="next"
                           title="{{ art_next.title }}">
                            {{ art_next.title }}&nbsp;&nbsp;>>
                        </a>
                        {% else %}
                        <a href="javascript:;" style="float:right">
                            没有文章啦!!!
                        </a>
                        {% endif %}
                    </div>
                    <br>
                    <h3>评论列表:</h3>
                    {% for comment in comment_list %}
                    <p><a href="#{{forloop.counter}}">#{{forloop.counter}}楼</a><a name="{{forloop.counter}}"></a>
                        &nbsp;&nbsp;{{comment.add_time|date:'Y-m-d H:i:s'}}&nbsp;&nbsp;
                        <a href="{% url 'show:a_contact' %}?id={{comment.user.id}}">{{comment.user.name}}</a>&nbsp;&nbsp;
                        {% if comment.user_id == art.user_id %}<font color="red">[楼主]</font>{% endif %}
                    </p>
                    <h5>{{comment.content}}</h5>
                    {% endfor %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <h3>我要评论:</h3>
                        <textarea name="comment" cols="50" rows="5"></textarea>
                        <input type="submit" name="sub" value="提交">
                    </form>
                </div>
            </div>

        </div>
    </div>


    <!-- END row -->

    <section class="probootstrap-section">
        <div class="container-fluid">
            <div class="row mb-5 justify-content-center">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-8 mx-auto">
                            <h2 class="h1 mb-5 mt-0">最新文章</h2>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="owl-carousel probootstrap-owl">
                        {% for art in new_art_list %}
                        <div class="item" onclick="jump({{art.id}});">
                            <img src="/media/{{art.title_img}}" width="370px" height="250px"
                                 alt="图片加载中...">
                            <div class="p-4 border border-top-0">
                                <h4>{{art.title}}</h4>
                                <p>{{art.describe}}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <script>
                function jump(id){
                    location.href = '/show/a_single/?id='+id;
                }
            </script>


        </div>
    </section>
    <!-- END section -->

</div>


{% endblock %}

templates/a_tag.html
{% extends 'a_base.html' %}
{% block title %}
<title>标签云</title>
{% endblock %}
{% block content %}
<style>
body {background: gray;}
#div1 {position:relative; width:450px; height:450px; margin: 20px auto 0; }
#div1 a {position:absolute; top:0px; left:0px; font-family: Microsoft YaHei; color:#fff; font-weight:bold; text-decoration:none; padding: 3px 6px; }
#div1 a:hover {border: 1px solid #eee; background: #000; }
#div1 .blue {color:blue;}
#div1 .red {color:red;}
#div1 .yellow {color:yellow;}
#div1 p { font: 16px Microsoft YaHei; text-align: center; color: #ba0c0c; }
#div1 p a { font-size: 14px; color: #ba0c0c; }
#div1 p a:hover { color: red; }
#div1 p a:hover {color:red; }

</style>
<script type="text/javascript" src="/static/a_js/miaov.js"></script>
<div id="div1">
    {% for lab in lab_list %}
    <a href="{% url 'show:a_tag' %}?id={{lab.id}}">{{lab.name}}</a>
    {% endfor %}
</div>
{% endblock %}

templates/art_list_cate.html
{% extends 'base_main.html' %}
{% block title %}
<title>目录文章</title>
{% endblock %}

{% block content%}
{{block.super}}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
    <form action="/Article/checkAll" method="post">
        <h1 class="page-header">操作</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'myblog:add_article' %}?c_id={{art_list.0.id}}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{art_list.1.0}}</span></h1>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span>
                    </th>
                    <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                    <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">父栏目</span></th>
                    <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                    <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span
                            class="visible-lg">标签</span></th>
                    <th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span
                            class="visible-lg">评论</span></th>
                    <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">发布日期</span></th>
                    <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">最后更新</span></th>
                </tr>
                </thead>
                <tbody>
                {% for a in art_list.1.1 %}
                <tr>
                    <td><input type="checkbox" class="input-control" name="checkbox[]" value=""/></td>
                    <td class="article-title">{{a.title}}</td>
                    <td>{% if a.col.columns %}{{a.col.columns.name}}{% else %}无{% endif %}</td>
                    <td>{{a.col.name}}</td>
                    <td class="hidden-sm">{% for l in a.lab.all %}{% if forloop.last %}{{l.name}}{% else %}{{l.name}},{% endif %}{% endfor %}</td>
                    <td class="hidden-sm">{{a.com.count}}</td>
                    <td>{{a.add_time|date:'Y-m-d H:i:s'}}</td>
                    <td>{{a.update_time|date:'Y-m-d H:i:s'}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <footer class="message_footer">
            <nav>
                <div class="btn-toolbar operation" role="toolbar">
                    <div class="btn-group" role="group"><a class="btn btn-default" onClick="select()">全选</a> <a
                            class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default"
                                                                                  onClick="noselect()">不选</a>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom"
                                title="删除全部选中" name="checkbox_delete">删除
                        </button>
                    </div>
                </div>
                <ul class="pagination pagenav">
                    <li {% if not art_list.has_previous %} class="disabled" {% endif %}><a href="{% if art_list.has_previous %}{% url 'myblog:article' %}?page={{art_list.previous_page_number}}{% else %}javascript:void(0){% endif %}" aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a></li>
                    {% for pg in art_list.paginator.page_range %}
                    <li {% if pg == art_list.number %} class="active" {% endif %}><a href="{% url 'myblog:article' %}?page={{pg}}">{{pg}}</a></li>
                    {% endfor %}
                    <li {% if not art_list.has_next %} class="disabled" {% endif %}><a href="{% if art_list.has_next %}{% url 'myblog:article' %}?page={{art_list.next_page_number}} {% else %}javascript:void(0){% endif %}" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a></li>
                </ul>
            </nav>
        </footer>
    </form>
</div>
{% endblock %}
{% block js%}
{{block.super}}
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText == "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/myblog/delete_article/",
					data: {
					    'id':id
					},
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
</script>
{% endblock %}

templates/article.html
{% extends 'base_main.html' %}
{% block title %}
<title>博客文章</title>
{% endblock %}

{% block content%}
{{block.super}}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
    <form action="/Article/checkAll" method="post">
        <h1 class="page-header">操作--><a href="{% url 'show:a_index' %}">前往前台</a></h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'myblog:add_article' %}">增加文章</a></li>
        </ol>
        <h1 class="page-header">管理 <span class="badge">{{art_list.paginator.count}}</span></h1>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span>
                    </th>
                    <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">标题</span></th>
                    <th><span class="glyphicon glyphicon-list"></span> <span class="visible-lg">栏目</span></th>
                    <th class="hidden-sm"><span class="glyphicon glyphicon-tag"></span> <span
                            class="visible-lg">标签</span></th>
                    <th class="hidden-sm"><span class="glyphicon glyphicon-comment"></span> <span
                            class="visible-lg">评论</span></th>
                    <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">发布日期</span></th>
                    <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">最后更新</span></th>
                    <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
                </thead>
                <tbody>
                {% for art in art_list %}
                <tr>
                    <td><input type="checkbox" class="input-control" name="checkbox[]" value=""/></td>
                    <td class="article-title">{{art.title}}</td>
                    <td>{{art.col.name}}</td>
                    <td class="hidden-sm">{% for l in art.lab.all %}{% if forloop.last %}{{l.name}}{% else %}{{l.name}},{% endif %}{% endfor %}</td>
                    <td class="hidden-sm">{{art.com.count}}</td>
                    <td>{{art.add_time|date:'Y-m-d H:i:s'}}</td>
                    <td>{{art.update_time|date:'Y-m-d H:i:s'}}</td>
                    <td><a href="{% url 'myblog:update_article' %}?id={{art.id}}">修改</a> <a rel="{{art.id}}">删除</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <footer class="message_footer">
            <nav>
                <div class="btn-toolbar operation" role="toolbar">
                    <div class="btn-group" role="group"><a class="btn btn-default" onClick="select()">全选</a> <a
                            class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default"
                                                                                  onClick="noselect()">不选</a>
                    </div>
                    <div class="btn-group" role="group">
                        <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom"
                                title="删除全部选中" name="checkbox_delete">删除
                        </button>
                    </div>
                </div>
                <ul class="pagination pagenav">
                    <li {% if not art_list.has_previous %} class="disabled" {% endif %}><a href="{% if art_list.has_previous %}{% url 'myblog:article' %}?page={{art_list.previous_page_number}}{% else %}javascript:void(0){% endif %}" aria-label="Previous"> <span aria-hidden="true">&laquo;</span> </a></li>
                    {% for pg in art_list.paginator.page_range %}
                    <li {% if pg == art_list.number %} class="active" {% endif %}><a href="{% url 'myblog:article' %}?page={{pg}}">{{pg}}</a></li>
                    {% endfor %}
                    <li {% if not art_list.has_next %} class="disabled" {% endif %}><a href="{% if art_list.has_next %}{% url 'myblog:article' %}?page={{art_list.next_page_number}} {% else %}javascript:void(0){% endif %}" aria-label="Next"> <span aria-hidden="true">&raquo;</span> </a></li>
                </ul>
            </nav>
        </footer>
    </form>
</div>
{% endblock %}
{% block js%}
{{block.super}}
<script>
//是否确认删除
$(function(){
	$("#main table tbody tr td a").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id
		if (event.srcElement.outerText == "删除")
		{
			if(window.confirm("此操作不可逆，是否确认？"))
			{
				$.ajax({
					type: "POST",
					url: "/myblog/delete_article/",
					data: {
					    'id':id
					},
					cache: false, //不缓存此页面
					success: function (data) {
						window.location.reload();
					}
				});
			};
		};
	});
});
</script>
{% endblock %}

templates/comment.html
{% extends 'base_main.html' %}
{% block title %}
<title>评论</title>
{% endblock %}
{% block content%}
{{block.super}}
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <form action="/Comment/checkAll" method="post">
        <h1 class="page-header">管理 <span class="badge">{{result.paginator.count}}</span></h1>
        <div class="table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th><span class="glyphicon glyphicon-th-large"></span> <span class="visible-lg">选择</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">评论人</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">评论文章</span></th>
                <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">摘要</span></th>
                <th><span class="glyphicon glyphicon-time"></span> <span class="visible-lg">日期</span></th>
                <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
              </tr>
            </thead>
            <tbody>
            {% for c in result %}
              <tr>
                <td><input type="checkbox" class="input-control" name="checkbox[]" value="" /></td>
                <td class="article-title">{{c.0}}</td>
                <td class="article-title">{{c.1}}</td>
                <td class="article-title">{{c.2}}</td>
                <td>{{c.3|date:'Y-m-d'}}</td>
                <td><a rel="{{c.4}}" name="delete">删除</a></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <footer class="message_footer">
          <nav>
            <div class="btn-toolbar operation" role="toolbar">
              <div class="btn-group" role="group"> <a class="btn btn-default" onClick="select()">全选</a> <a class="btn btn-default" onClick="reverse()">反选</a> <a class="btn btn-default" onClick="noselect()">不选</a> </div>
              <div class="btn-group" role="group">
                <button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="删除全部选中" name="checkbox_delete">删除</button>
              </div>
            </div>
            <ul class="pagination pagenav">
              <li {% if result.has_previous == False %}class="disabled"{% endif %}>
                <a {% if result.has_previous %}href="{% url 'myblog:comment' %}?page={{result.number|add:'-1'}}" {% else %} href ="javascript:;" {% endif %} aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              {% for p in result.paginator.page_range %}
              <li {% if p == result.number %}class="active"{% endif %}>
                <a href="{% url 'myblog:comment' %}?page={{p}}">{{forloop.counter}}
                </a>
              </li>
              {% endfor %}
              <li {% if result.has_next == False %}class="disabled"{% endif %}>
                <a {% if result.has_next %}href="{% url 'myblog:comment' %}?page={{result.number|add:'1'}}" {% else %} href ="javascript:;" {% endif %} aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
        </footer>
      </form>
    </div>
{% endblock %}
{% block js%}
{{block.super}}
<script src="/static/js/bootstrap.min.js"></script>
<script>
$(function () {
    $("#main table tbody tr td a").click(function () {
        var name = $(this);
        var id = name.attr("rel"); //对应id   
        if (name.attr("name") === "delete") {
            if (window.confirm("此操作不可逆，是否确认？")) {
                $.ajax({
                    type: "POST",
                    url: "/myblog/del_comment/",
                    data: "com_id=" + id,
                    cache: false, //不缓存此页面   
                    success: function (data) {
                        if(data.code == '200'){
                          window.location.reload();
                        }
                    }
                });
            };
        };
    });
});
</script>
{% endblock %}